# setting up cache for huggingface model

on:
  push:
    paths:
      - 'src/**'

jobs:
  cache_huggingface:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Cached models
        id: cache-mods
        uses: actions/cache@v3
        with:
          path: cache
          key: ${{runner.os}}-huggingmodel
      - name: Force download
        if: steps.cache-mods.outputs.cache-hit != 'false'
        run: |
          # here code to force download of model
          python -c "from src import sim_funcs"
      - name: Running test
        run: |
          # running
          python mod_test.py
      - run: echo "This job's status is ${{ job.status }}."
